* my git experience

** repository download, edit, upload, by git


*** summary

| the repsitory | the git command |
|---------------+-----------------|
| download      | git clone       |
|               |                 |
| edit          | git add         |
|               | git commit      |
|               |                 |
| upload        | git push        |

*** download THIS repository

| step |                              | the command                                          |
|------+------------------------------+------------------------------------------------------|
|    1 | open a terminal              |                                                      |
|      |                              |                                                      |
|    2 | point inside the terminal    |                                                      |
|      | move to the desire directory |                                                      |
|      |                              |                                                      |
|    3 | download the respostory      | git clone https://github.com/cmchaol/hello-world.git |


*** edit the local repository, git add, git commit

| step |                                  | the command               |
|------+----------------------------------+---------------------------|
|    1 | move inside the local repository | cd hello-world            |
|      |                                  |                           |
|    2 | edit the-specific-file           |                           |
|      |                                  |                           |
|    3 | git add the-specific-file        | git add the-specific-file |
|      |                                  |                           |
|    4 | commit the snapshot              | git commit -m "<message>" |


git add

https://www.atlassian.com/git/tutorials/saving-changes/git-add


git commit 

https://www.atlassian.com/git/tutorials/saving-changes/git-commit



*** upload the local snapshot to the remote github repository

| step |                             |
|------+-----------------------------|
|    1 | inside the local repository |
|      |                             |
|    2 | git push                    |

git push 

https://www.atlassian.com/git/tutorials/syncing/git-push


*** a typical script

| A practicle cycle |
|-------------------|
| git clone         |
| edit              |
| git add           |
| git commit        |
| git push          |

#+BEGIN_EXAMPLE
git add hello-world-201410.org

git commit -m "<another modification of hello-world-201410.org>"

git push
#+END_EXAMPLE



** Caching your GitHub password in Git

https://help.github.com/articles/caching-your-github-password-in-git

#+BEGIN_EXAMPLE
git config          credential.helper  cache

git config --global credential.helper  cache

git config --global credential.helper 'cache --timeout=3600'
#+END_EXAMPLE



* org mode

** synonym

|          | reference |
|----------+-----------|
| orgmode  |         1 |
|          |           |
| org mode |         1 |
|          |           |
| org-mode |         3 |
|          |           |
| org      |         2 |
|          |           |
|          |           |


reference

1

http://orgmode.org/


2

http://orgmode.org/manual/Summary.html#Summary


3

http://en.wikipedia.org/wiki/Org-mode


** org export backends

c-h v org-export-backends

** org export Literal examples

http://orgmode.org/manual/Literal-examples.html#Literal-examples

: #+BEGIN_EXAMPLE
: Some example from a text file.
: #+END_EXAMPLE

For simplicity when using small examples, you can also start the example lines with a colon followed by a space. There may also be additional whitespace before the colon:

     Here is an example
        : Some example from a text file.
#+BEGIN_EXAMPLE
     Here is an example
        : Some example from a text file.
#+END_EXAMPLE



* R

** installation in gentoo

emerge -s %^R$ 

These days, if you want a regex search, you have to prepend a "%" and the regex search is case sensitive. 

http://forums.gentoo.org/viewtopic-t-129047.html

man emerge

--search (-s)
              Searches  for  matches of the supplied string in the portage tree.  By default emerge uses a case-insensitive simple search, but you can enable a regular expression search by prefixing the search string with %.  For example, emerge --search "%^kde" searches for any package whose name starts with "kde"; emerge --search "%gcc$" searches for any package that ends with "gcc"; emerge --search "office" searches for any package that contains the word "office".  If you want to include the category into the search string, prepend an @: emerge --search "%@^dev-java.*jdk". If you  want  to  search the package descriptions as well, use the --searchdesc action.



 emerge -s %^R$ 
Searching...    
[ Results for search key : ^R$ ]
[ Applications found : 1 ]

dev-lang/R
      Latest version available: 3.0.1
      Latest version installed: 3.0.1
      Size of files: 24,910 kB
      Homepage:      http://www.r-project.org/
      Description:   Language and environment for statistical computing and graphics
      License:       || ( GPL-2 GPL-3 ) LGPL-2.1


** ESS

 emerge -s %^ess$

[ Results for search key : ^ess$ ]
[ Applications found : 2 ]

  app-emacs/ess
      Latest version available: 13.09
      Latest version installed: 13.09
      Size of files: 3,278 kB
      Homepage:      http://ess.r-project.org/
      Description:   Emacs Speaks Statistics
      License:       GPL-2+ GPL-3+ Texinfo-manual

  app-xemacs/ess
      Latest version available: 1.03
      Latest version installed: [ Not Installed ]
      Size of files: 459 kB
      Homepage:      http://xemacs.org/
      Description:   ESS: Emacs Speaks Statistics
      License:       GPL-2

